Algoritmo "exercicio8"
// Desenvolver um programa que apresente todos os valores numéricos
// inteiros ímpares situados na faixa de 0 a 20. Para saber se o número
// é ímpar, será necessário verificar essa condição com o comando if.
// Sendo ímpar, mostre-o; não sendo, passe para o próximo passo.

Var
cont: inteiro

Inicio
cont <- 0

enquanto ( cont <= 20 ) faca
         se ( cont % 2 = 1 ) entao
            escreval(cont)
         fimse
         cont <- cont + 1
fimenquanto



Fimalgoritmo