Algoritmo "Exercicio01"
//Pergunte um número ao usuario e informe
//se este numero é par ou ímpar

Var
// Seção de Declarações das variáveis
 numero : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval("Digite um numero: ")
leia(numero)

resto <- numero % 2

se ( resto = 0 ) entao
   escreva(num, " é par")
senao
     escreval (num, "é impar")
fimse


Fimalgoritmo