Algoritmo "Exercicio01"
//Fazer um algoritmo que peça um número, e ao final, informe se o número
//digitado está acima de 1000 ou
//abaixo de 1000
Var
// Seção de Declarações das variáveis 
num1: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe um numero: ")
leia(num1)

se (num1 >= 1000) entao
   escreval("O número informado está acima de 1000")
senao
     escreval("O número informado está abaixo de 1000")
fimse

Fimalgoritmo